version: "3"
services:
  app:
    container_name: next-app
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: npm run start
    environment:
      NODE_ENV: production
      PORT: 3000
      HOST: 0.0.0.0
    expose:
      - "3000"
    networks:
      - nextjs-network
  nginx:
    container_name: nginx-proxy
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9090:80"
    depends_on:
      - app
    networks:
      - nextjs-network
networks:
  nextjs-network:
volumes:
  nextjs-app: